require 'pry'
require 'nokogiri'
require 'open-uri'
require 'net/http'
require 'json'

require_relative '../lib/app/scraper'
require_relative '../lib/environment'
require_relative '../lib/app/cli'
require_relative '../lib/app/truckstop'
